### PR TITLE
Update dbt to 1.6

### PR DESCRIPTION
**Pull request by ian-r-rose**
Doing some version bumps and associated maintenance here in preparation for using the template

### CODE REVIEW

**Comment by AeriShan-ODI** [comment]
I have no idea what to review or test here

**Comment by ian-r-rose** [comment]
If you want to test it locally, I'm also curious to hear how it goes.

**Comment by AeriShan-ODI** [comment]
What is the "copier" utility?

**Comment by AeriShan-ODI** [comment]
I'm supposed to read the docs??? 😱

**Review by AeriShan-ODI — APPROVED** [review]
Looks good to me

**Pull request merged**
